### ISSUE TITLE
How to set openai client timeout when using OpenAIEmbeddings?

### ISSUE THREAD

**Issue by sing1ee** [hwchase17/langchain#1416]
code like this:
```shell
faiss_index = FAISS.from_texts(textList, OpenAIEmbeddings())
```
How to set timeout of OpenAIEmbeddings?  Thx

**Comment by sing1ee** [comment]
There are three code segments, I think the timeout parameter can be explicitly set, and the user can pass it in when using OpenAIEmbeddings.
```shell
response = self.client.create(
                    input=tokens[i : i + chunk_size], engine=self.document_model_name
                )
```
```shell
return self.client.create(input=[text], engine=engine)["data"][0][
                "embedding"
            ]
```
```shell
response = self.client.create(
                    input=texts[i : i + chunk_size], engine=self.document_model_name
                )
```

**Comment by sing1ee** [comment]
more details, error
```shell
Traceback (most recent call last):
  File "build_index.py", line 43, in <module>
    faiss_index = FAISS.from_texts(textList, OpenAIEmbeddings())
  File "/usr/local/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 250, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/usr/local/lib/python3.8/site-packages/langchain/embeddings/openai.py", line 152, in embed_documents
    response = self.client.create(
  File "/usr/local/lib/python3.8/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/usr/local/lib/python3.8/site-packages/openai/api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x129cb4f40>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```
The following code only captures the exception of OpenAIError, and does not handle the exception of the network, so it is necessary to be able to set the timeout of openai? Or catch network exceptions here and do a limited number of retries? Explicitly setting the timeout is a better choice
```shell
while True:
            try:
                response = super().create(*args, **kwargs)

                # If a user specifies base64, we'll just return the encoded string.
                # This is only for the default case.
                if not user_provided_encoding_format:
                    for data in response.data:

                        # If an engine isn't using this optimization, don't do anything
                        if type(data["embedding"]) == str:
                            assert_has_numpy()
                            data["embedding"] = np.frombuffer(
                                base64.b64decode(data["embedding"]), dtype="float32"
                            ).tolist()

                return response
            except TryAgain as e:
                if timeout is not None and time.time() > start + timeout:
                    raise

                util.log_info("Waiting for model to warm up", error=e)
```
