### ISSUE TITLE
Tiktoken version is too old for `gpt-3.5-turbo`

### ISSUE THREAD

**Issue by xingfanxia** [hwchase17/langchain#1881]
```
Traceback (most recent call last):
  File "/Users/xingfanxia/projects/notion-qa/qa.py", line 25, in <module>
    result = chain({"question": args.question})
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/qa_with_sources/base.py", line 118, in _call
    answer, _ = self.combine_documents_chain.combine_docs(docs, **inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/combine_documents/map_reduce.py", line 143, in combine_docs
    return self._process_results(results, docs, token_max, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/combine_documents/map_reduce.py", line 173, in _process_results
    num_tokens = length_func(result_docs, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 83, in prompt_length
    return self.llm_chain.llm.get_num_tokens(prompt)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 331, in get_num_tokens
    enc = tiktoken.encoding_for_model(self.model_name)
  File "/opt/homebrew/lib/python3.10/site-packages/tiktoken/model.py", line 51, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-3.5-turbo to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'
```

**Comment by harithzulfaizal** [comment]
I seem to be encountering the same issue when using `gpt-4` despite having the latest version of Tiktoken. Any ideas as to why?

**Comment by plchld** [comment]
I get the same issue when i use AzureOpenAI gpt 3.5

```bash
KeyError                                  Traceback (most recent call last)
Cell In[69], line 22
     20 PROMPT = PromptTemplate(template=prompt_template, input_variables=["text"])
     21 chain = load_summarize_chain(gpt35, chain_type="map_reduce", return_intermediate_steps=True, map_prompt=PROMPT, combine_prompt=PROMPT)
---> 22 chain({"input_documents": docs}, return_only_outputs=True)

File [~/.pyenv/versions/3.10.0/envs/local/lib/python3.10/site-packages/langchain/chains/base.py:116](https://file+.vscode-resource.vscode-cdn.net/Users/nikolasmolyndris/OSINT/Projects/News-Copilot/~/.pyenv/versions/3.10.0/envs/local/lib/python3.10/site-packages/langchain/chains/base.py:116), in Chain.__call__(self, inputs, return_only_outputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116     raise e
    117 self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118 return self.prep_outputs(inputs, outputs, return_only_outputs)

File [~/.pyenv/versions/3.10.0/envs/local/lib/python3.10/site-packages/langchain/chains/base.py:113](https://file+.vscode-resource.vscode-cdn.net/Users/nikolasmolyndris/OSINT/Projects/News-Copilot/~/.pyenv/versions/3.10.0/envs/local/lib/python3.10/site-packages/langchain/chains/base.py:113), in Chain.__call__(self, inputs, return_only_outputs)
    107 self.callback_manager.on_chain_start(
    108     {"name": self.__class__.__name__},
    109     inputs,
    110     verbose=self.verbose,
    111 )
    112 try:
--> 113     outputs = self._call(inputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
...
     72         "Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect."
     73     ) from None
     75 return get_encoding(encoding_name)

KeyError: 'Could not automatically map gpt-35-turbo to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'
```

**Comment by awhillas** [comment]
Seems to be setup to handle the latest https://github.com/openai/tiktoken/blob/main/tiktoken/model.py#L13

**Comment by peterjhwang** [comment]
I had the same issue. It works for me after updating tiktoken version.

**Comment by sangeetkumar1988** [comment]
> 

Hi Peter, I'm facing the same issue. Can you please let me know the tiktoken version you sue to resolve the issue. As I have updated it to the latest version and langchain also has the updated version. But still it's giving the error

**Comment by peterjhwang** [comment]
At the moment, I am using. 
tiktoken==0.4.0
langchain==0.0.178
You can check the model you are using is included in MODEL_TO_ENCODING from here.
https://github.com/openai/tiktoken/blob/main/tiktoken/model.py

**Comment by sangeetkumar1988** [comment]
> At the moment, I am using. tiktoken==0.4.0 langchain==0.0.178 You can check the model you are using is included in MODEL_TO_ENCODING from here. https://github.com/openai/tiktoken/blob/main/tiktoken/model.py

Thanks for your response. just to know if we can use gpt-35-turbo for text summarization?

**Comment by sangeetkumar1988** [comment]
Any idea why chain_type='map_reduce' can't be used with custom prompt template. Like if we mention chain_type='map_reduce' the method doesn't accept prompt=PROMPT.

**Comment by NageshMashette** [comment]
> > At the moment, I am using. tiktoken==0.4.0 langchain==0.0.178 You can check the model you are using is included in MODEL_TO_ENCODING from here. https://github.com/openai/tiktoken/blob/main/tiktoken/model.py
> 
> Thanks for your response. just to know if we can use gpt-35-turbo for text summarization or RetrievalQuestionAnswering kind of work?

yes you can use.
