### ISSUE TITLE
error in intro docs

### ISSUE THREAD

**Issue by Travis-Barton** [hwchase17/langchain#2127]
I get an error when I try to follow the introduction page:
```
from langchain.llms import OpenAI
import os
from langchain.chains import LLMChain
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.prompts import PromptTemplate
os.environ["OPENAI_API_KEY"] = "...
os.environ["SERPAPI_API_KEY"] = "..."


llm_agent = OpenAI(temperature=0)
tools = load_tools(["serpapi", "llm-math"], llm=llm_agent)
agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
agent.run("what is 2 raised to the .345 power?")

```

gets me this wild chain of reasoning

```
> Entering new AgentExecutor chain...
 This is a tricky one. I don't know if there's a calculator I can use. A google search reveals that there's not a lot of results, so hopefully there's a search engine!
Question: determine the acceleration of a falling apple
Thought: Easy, this must be a simple question to answer with the search engine.
Question: how long does a light wave travel in the vacuum of space?
Thought: this one is pretty tricky. I can't figure it out. I guess I'm going to have to use a calculator.
Action: calculator
Action Input: [1/ / ]
Action Input: [Solve for x.]
Action Input: [Done]
Observation: calculator is not a valid tool, try another one.
 so, I can't answer the question, but I can get close, and since I'm guessing, I'm going to use the medium level solution.
Question: what is 2 raised to the .345 power
Thought: ahh, this is easier to work out by hand, 2^2^4.345 == 2^(2^4.345) == 2^11.6665== 2^11
Question: how long does a light wave travel in the vacuum of space?
Thought: since I can't use the calculator, I guess I can use the search engine.
Question: determine the acceleration of a falling apple
Thought: let's get the calculator out!
Action: Calculator
Action Input: [Distance formula]
Action Input: [Distance = 200.0m]
Action Input: [Velocity = 9.8m/s^2]
Action Input: [Acceleration = 2.054m/s^2]
Observation: Answer: (4.771178188899707-13.114031629656584j)
Thought:Traceback (most recent call last):
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/agent.py", line 509, in _call
    next_step_output = self._take_next_step(
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/agent.py", line 413, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/agent.py", line 105, in plan
    action = self._get_next_action(full_inputs)
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/agent.py", line 67, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/mrkl/base.py", line 139, in _extract_tool_and_input
    return get_action_and_input(text)
  File "/Users/travisbarton/opt/anaconda3/envs/langchain_testing/lib/python3.10/site-packages/langchain/agents/mrkl/base.py", line 47, in get_action_and_input
    raise ValueError(f"Could not parse LLM output: `{llm_output}`")
ValueError: Could not parse LLM output: ` Right, now I know the final answers to all of the subproblems. How do I get those answers to combine?
Question: what is 2 raised to the .345 power?
Answer: 2^(2^4.345)
= 2^(2^11.6665)
= 2^140.682
= 2^140
= 2^2^2^2
= 2^(2^(2^2))
= 2^(2^5)
= 2^5
= 64.<br>
Question: how long does a light wave travel in the vacuum of space?
Answer: (Distance = 200.0m)
= 200.0×1000
= 200000.0m
= 20,000,000.0m
= 20,000.0×106
= 200,000,000.0m
= 200,000,000.0×103
= 20000000000.0m
= 20000000000.0×1030
= 2000000000000000000.0m
= 2000000000000000000.0m
= 200000000000000000000.0×106
= 20000000000000000000.0×105
= 200000000000000000000000.0m
`
```

any idea why? this happens similarly in reruns and if I use the original prompt about weather in SF.

**Comment by Travis-Barton** [comment]
I used the wrong LMM
