### ISSUE TITLE
Unable to run 'Getting Started' example with due to numpy error

### ISSUE THREAD

**Issue by Gingernaut** [hwchase17/langchain#2131]
Firs time attempting to use this project on an M2 Max Apple laptop, using the example code in the guide

```python
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.llms import OpenAI

self.openai_llm = OpenAI(temperature=0)

tools = load_tools(["serpapi", "llm-math"], llm=self.openai_llm)
agent = initialize_agent(
    tools, self.openai_llm, agent="zero-shot-react-description", verbose=True
)
agent.run("what is the meaning of life?")

```

```
Traceback (most recent call last):
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/numpy/core/__init__.py", line 23, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/numpy/core/multiarray.py", line 10, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/numpy/core/overrides.py", line 6, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tpeterson/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tpeterson/.pyenv/versions/3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/__main__.py", line 2, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/app/main.py", line 6, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/__init__.py", line 5, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/agents/__init__.py", line 2, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/agents/agent.py", line 15, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/chains/__init__.py", line 2, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/chains/api/base.py", line 8, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/chains/api/prompt.py", line 2, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/prompts/__init__.py", line 11, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/prompts/few_shot.py", line 11, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/prompts/example_selector/__init__.py", line 3, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/prompts/example_selector/semantic_similarity.py", line 8, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/embeddings/__init__.py", line 6, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/langchain/embeddings/fake.py", line 3, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/numpy/__init__.py", line 141, in <module>
  File "/Users/tpeterson/Code/ai_software/newluna/./luna/numpy/core/__init__.py", line 49, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/tpeterson/Code/ai_software/newluna/.venv/bin/python"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

**Comment by aarora79** [comment]
While this issue is closed, for anyone stumbling upon this, I had the same problem while using langchain in AWS Lambda, the way I resolved this by downloading the numpy files from [here](https://files.pythonhosted.org/packages/f4/f4/45e6e3f7a23b9023554903a122c95585e9787f9403d386bafb7a95d24c9b/numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) from the [PyPi numpy files](https://pypi.org/project/numpy/1.24.2/#files) download page. Once downloaded, unzip the whl into your virtual environment's `site-packages` directory.

**Comment by dexinhuang** [comment]
> While this issue is closed, for anyone stumbling upon this, I had the same problem while using langchain in AWS Lambda, the way I resolved this by downloading the numpy files from [here](https://files.pythonhosted.org/packages/f4/f4/45e6e3f7a23b9023554903a122c95585e9787f9403d386bafb7a95d24c9b/numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) from the [PyPi numpy files](https://pypi.org/project/numpy/1.24.2/#files) download page. Once downloaded, unzip the whl into your virtual environment's `site-packages` directory.

Hi, I am also running into the same issue. I am on a Windows machine and downloaded the Windows version. It didn't seem to work for me and I am still running into the issue. I am uploading all my code with the packages as a zip. Are there any workarounds? Thanks!

**Comment by ishaan812** [comment]
Same issue here, pls help
