### ISSUE TITLE
error when there are quotation marks in prompt template string

### ISSUE THREAD

**Issue by xlbao123** [hwchase17/langchain#2212]
hi, I want to include json data in the template, the code and error is as follows, please help me to solve it.

```python
from langchain.chat_models import ChatOpenAI
from langchain import PromptTemplate, LLMChain
from langchain.chains import ConversationChain
from langchain.prompts.chat import SystemMessagePromptTemplate

system = r'Me: Set an alarm\nYou: {"content":{"type":"alarm","time":"17:00"}}'
system_prompt = SystemMessagePromptTemplate.from_template(system)
#system_prompt = SystemMessagePromptTemplate.from_template(system.replace('"', '\\"'))
```

the error is:
```bash
Traceback (most recent call last):
  File "/mnt/d/works/chatgpt-cli/tt.py", line 8, in <module>
    system_prompt = SystemMessagePromptTemplate.from_template(system.replace('"', '\\"'))
  File "/home/xlbao/.local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 67, in from_template
    prompt = PromptTemplate.from_template(template)
  File "/home/xlbao/.local/lib/python3.9/site-packages/langchain/prompts/prompt.py", line 130, in from_template
    return cls(input_variables=list(sorted(input_variables)), template=template)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input parameters. '\\"type\\"' (type=value_error)
```

**Comment by gpt4thewin** [comment]
Had the same issue.
Turned out that the cause was not the quotes but the brackets `{` `}`
You can escape them: replace with `{{` `}}`

**Comment by Kaotic3** [comment]
Is there not a better solution?

Should the prompt be validating string literals that you send it? Should it be looking inside that variable for curly braces?

What purpose does that serve?  We are sending plain text to a LLM - why are you checking for curly braces?

**Comment by smargoli2** [comment]
I am using double curly braces and still getting the error.
```
template="""Given an input question, first create a syntactically correct MSSQL SERVER query to run based on the database schema, then look at the results of the query and return the answer.
        Use the following format:

        Question: "Question here"
        SQLQuery: "SQL Query to run"
        SQLResult: "Result of the SQLQuery"
        Answer: "Final answer here"

        Question: {{input}}"""
    prompt = PromptTemplate(
        input_variables=["input"],
        template=template,
    )
agent_executor = create_sql_agent(
        llm=AzureChatOpenAI(temperature=0, model_name="gpt-35-turbo", openai_api_type="azure", openai_api_base="https://xxx.openai.azure.com/", openai_api_version="2023-05-15", deployment_name="xxx", prompt=prompt),
        toolkit=toolkit,
        verbose=True,
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        prefix=
        """Given an input question, first create a syntactically correct MSSQL query to run, then look at the results of the query and return the answer.
        Alias the tables in the query to avoid ambiguity. The Model Number is stored in the Number column of the Models table. DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database. If the question does not seem related to the database, just return "I don\'t know" as the answer.
        DO NOT use backticks before and after the query in the action input, even it it a multiline query. It causes syntax errors so the query can't run. This is important!"""
    )
    await agent_executor.arun(input=query)
```
