### ISSUE TITLE
Number of requested results 4 cannot be greater than number of elements in index 2

### ISSUE THREAD

**Issue by try-agaaain** [hwchase17/langchain#2255]
I write my code according to `docs/modules/chains/index_examples/vector_db_qa.ipynb`, but the following error happened:
```console
Using embedded DuckDB without persistence: data will be transient
Traceback (most recent call last):
  File "/home/todo/intership/GPTtrace/try.py", line 76, in <module>
    qa.run(query=query, k=1)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/chains/base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 109, in _call
    docs = self._get_docs(question)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 163, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 154, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 136, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search_with_score
    results = self._collection.query(
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 203, in query
    return self._client._query(
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/chromadb/api/local.py", line 247, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 521, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/home/todo/anaconda3/envs/gpt/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 228, in get_nearest_neighbors
    raise NotEnoughElementsException(
chromadb.errors.NotEnoughElementsException: Number of requested results 4 cannot be greater than number of elements in index 2
```

My code is following:
```python
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
import os
os.environ['OPENAI_API_KEY']="sk-..."

from langchain.document_loaders import TextLoader
loader = TextLoader("./prompts/text.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
docsearch = Chroma.from_documents(texts, embeddings)

qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=docsearch.as_retriever())

query = "What did the president say about Ketanji Brown Jackson"
qa.run(query)
```

It's seems relate to the content of text file passed to the `TextLoader`, when I pass the `langchain/docs/modules/state_of_the_union.txt`, It's can work well. It's very strange.

**Comment by nasirus** [comment]
this is happen when you have a small number of documents in Chroma , by default a retriever use similarity_search wich have a default value k = 4,
Try to set 
`qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=docsearch.as_retriever(search_kwargs={"k": 1}))`

**Comment by try-agaaain** [comment]
Thanks a lot.

**Comment by qaiwiz** [comment]
Is there anyway to feed search_kwargs={"k": 1} whenever calling the retriever? Assume, I create an index using CreateVectorIndex, and then def ret = index.vectorstore.as_retriever(). Unfortunately it doesn't accept search_kwargs={"k": 1} here! Something like feeding into ret.get_relevant_documents.

**Comment by svk-cu-nlp** [comment]
qa = ChatVectorDBChain.from_llm(ChatOpenAI(openai_api_key=OPENAI_API_KEY, temperature=0), docsearch, qa_prompt=prompt, top_k_docs_for_context=1)

**Comment by HMS97** [comment]
There are two ways to solve this bug. 
###  One is to convert the text.txt into this format, should be a blank line in every two line.
```
Frame 0 to 4: visual_text: The summary for frame 0 to 4 is: four different images of the logo for kinokick 2. a close up of the logo on the side of the building.
3. a close up of the logo on the side of the building 4. a blurred background with a red and purple background.  4. aspech_text:  At frame 0 to 2, UNKNOW says:  We'll be going in short-handed, you know?Frame 0 to 4 text end. 
 
Frame 4 to 8: visual_text: The summary for frame 4 to 8 is: four different shots of a woman in a roomthe movie is a comedy, the scene is a scene of a woman in a bar, the 1. of the earth from the perspective of the earth 2. of the woman in the middle of the room, looking at the globeThe woman is looking at the earth from the windowThe woman is looking at the earthspech_text:  At frame 0 to 2, UNKNOW says:  We'll be going in short-handed, you know?At frame 2 to 4, UNKNOW says:  Look, you still got the stones, so...At frame 4 to 5, SPEAKER_03 says:  So let's get him.Frame 4 to 8 text end. 
 
Frame 8 to 12: visual_text: The summary for frame 8 to 12 is: the movie is showing a woman in a room with a man and a womanthe earth is flat 1. of the earth 2. of the woman in the middle of the room, looking at the earthThe woman is in the kitchen, the man is in the living room, and the earth isThe woman is in the kitchen, the man is in the living room, the woman is inspech_text:  At frame 0 to 2, UNKNOW says:  We'll be going in short-handed, you know?At frame 2 to 4, UNKNOW says:  Look, you still got the stones, so...At frame 4 to 5, SPEAKER_03 says:  So let's get him.At frame 5 to 7, SPEAKER_03 says:  We used them to bring everyone back.At frame 7 to 8, SPEAKER_00 says:  Just like that.At frame 8 to 10, SPEAKER_00 says:  Yeah. Just like that.Frame 8 to 12 text end. 
 
Frame 12 to 16: visual_text: The summary for frame 12 to 16 is: four different shots of a woman in a black dressthe movie is called the girl on the train 1. of the woman in the black dress 2. of the woman in the black dress 3. of the woman in the black dressThe woman is looking at the cameraspech_text:  At frame 0 to 2, UNKNOW says:  We'll be going in short-handed, you know?At frame 2 to 4, UNKNOW says:  Look, you still got the stones, so...At frame 4 to 5, SPEAKER_03 says:  So let's get him.At frame 5 to 7, SPEAKER_03 says:  We used them to bring everyone back.At frame 7 to 8, SPEAKER_00 says:  Just like that.At frame 8 to 10, SPEAKER_00 says:  Yeah. Just like that.At frame 10 to 13, SPEAKER_00 says:  Even if there's a small chance that we can undo this,Frame 12 to 16 text end. 
 
```

### Another method is to split the text into multi docs, under each doc's contain token is less than 4096.
```
from langchain.chains.summarize import load_summarize_chain
from langchain.text_splitter import CharacterTextSplitter

from langchain.docstore.document import Document
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.chains import RetrievalQA,RetrievalQAWithSourcesChain
from langchain.document_loaders import TextLoader

from langchain.document_loaders import DirectoryLoader

import os
import shutil
def split_file(path, content, num_files):
    # Read the input file

    # Calculate the length of each chunk
    chunk_size = len(content) // num_files

    # Split the content into chunks
    chunks = [content[i:i+chunk_size] for i in range(0, len(content), chunk_size)]

    # Write each chunk to a separate file
    for i, chunk in enumerate(chunks):
        with open(f'{path}/{i+1}.txt', 'w') as f:
            f.write(chunk)
shutil.rmtree("text_dir", )
os.makedirs("text_dir")
with open('output.txt') as f:
    state_of_the_union = f.read()
split_file('text_dir', state_of_the_union,( numbers//1300 + 1))

```

### And then use the directory loader to load the dir. Then each db should also be less than 4096. This way spends time debugging.
```
embeddings = OpenAIEmbeddings()
# loader = TextLoader('summary_text.txt', encoding='utf8')
loader = DirectoryLoader('text_dir', glob="**/*.txt")

documents = loader.load()

# text_splitter = CharacterTextSplitter(chunk_size=44000,chunk_overlap=0)
text_splitter = CharacterTextSplitter(chunk_size=1100, chunk_overlap=0)

texts = text_splitter.split_documents(documents)

db = Chroma.from_documents(texts, embeddings)
```

**Comment by qixiaobo** [comment]
same problem here

**Comment by juanMarinero** [comment]
> split_file

`numbers` is not assigned, I tried with `numbers = len(state_of_the_union)` and it worked. Thanks a lot @HMS97 !!

Btw this answer lacks the last lines of original question (note old `docsearch` is here `db`):

```python
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", 
                                 retriever=db.as_retriever(search_kwargs={"k": 1}))

query = "What did the president say about Ketanji Brown Jackson"
qa.run(query)
```
Sidenote: if `loader.load()` error, then downgrade `unstructured` to version 0.6.1. [Link](https://github.com/hwchase17/langchain/issues/3726)

**Comment by completecode21** [comment]
import os
import sys

import constant
from langchain.document_loaders import TextLoader
from langchain.indexes import VectorstoreIndexCreator

os.environ["OPENAI_API_KEY"] = constant.APIKEY

print(len(sys.argv))
query = "what is mt dog name?"

loader = TextLoader('data.txt')
index = VectorstoreIndexCreator().from_loaders([loader])

print(index.query(query))



this is my code and i am getting error on my output :1
Number of requested results 4 is greater than number of elements in index 1, updating n_results = 1


what is my mistake please help me to get out of this

**Comment by christopherorea** [comment]
I get the same problem... This is the response i get

`WARNING:chromadb.segment.impl.vector.local_persistent_hnsw:Number of requested results 20 is greater than number of elements in index 15, updating n_results = 15`

Which seems odd. My configuration is the following

```
qa_chain = RetrievalQAWithSourcesChain.from_chain_type(
  llm,
  retriever=db.as_retriever(search_type="mmr", search_kwargs={"k": 1}), 
  chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
  memory=memory
)
```
