### ISSUE TITLE
ImportError: cannot import name 'LLMChain' from partially initialized module 'langchain'

### ISSUE THREAD

**Issue by galvana** [hwchase17/langchain#2371]
I'm trying to run the `LLMRequestsChain` example from the docs (https://python.langchain.com/en/latest/modules/chains/examples/llm_requests.html) but I am getting this error

```
(.venv) adriangalvan@eth-24s-MBP spec-automation % python3 requests.py
Traceback (most recent call last):
  File "/Users/adriangalvan/Desktop/spec-automation/requests.py", line 2, in <module>
    from langchain import LLMChain, OpenAI, PromptTemplate
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import Agent, AgentExecutor
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 13, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/agents/tools.py", line 5, in <module>
    from langchain.tools.base import BaseTool
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/tools/__init__.py", line 3, in <module>
    from langchain.tools.base import BaseTool
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/tools/base.py", line 8, in <module>
    from langchain.callbacks import get_callback_manager
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/callbacks/__init__.py", line 16, in <module>
    from langchain.callbacks.tracers import SharedLangChainTracer
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/callbacks/tracers/__init__.py", line 4, in <module>
    from langchain.callbacks.tracers.langchain import BaseLangChainTracer
  File "/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/callbacks/tracers/langchain.py", line 9, in <module>
    import requests
  File "/Users/adriangalvan/Desktop/spec-automation/requests.py", line 2, in <module>
    from langchain import LLMChain, OpenAI, PromptTemplate
ImportError: cannot import name 'LLMChain' from partially initialized module 'langchain' (most likely due to a circular import) (/Users/adriangalvan/Desktop/spec-automation/.venv/lib/python3.10/site-packages/langchain/__init__.py)
```

```
Python 3.10.8
```

**Comment by galvana** [comment]
The issue was naming my file `requests.py` I changed it to `requests_chain.py` and the issue went away.
