### ISSUE TITLE
vectorstores error: "search_phase_execution_exceptionm" after using elastic search

### ISSUE THREAD

**Issue by longgui0318** [hwchase17/langchain#2386]
# Hi

### I'm using elasticsearch as Vectorstores, just a simple call, but it's reporting an error, I've called add_documents beforehand and it's working. But calling similarity_search is giving me an error. Thanks for checking

# Related Environment
* docker >> image elasticsearch:7.17.0
* python >> elasticsearch==7.17.0

# Test code

```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import ElasticVectorSearch

if __name__ == "__main__":
    embeddings = OpenAIEmbeddings()
    elastic_vector_search = ElasticVectorSearch(
        elasticsearch_url="http://192.168.1.2:9200",
        index_name="test20222",
        embedding=embeddings
    )
    searchResult = elastic_vector_search.similarity_search("What are the characteristics of sharks")

```

# Error
```
(.venv) apple@xMacBook-Pro ai-chain % python test.py
Traceback (most recent call last):
  File "/Users/apple/work/x/ai-chain/test.py", line 14, in <module>
    result = elastic_vector_search.client.search(index="test20222",query={
  File "/Users/apple/work/x/ai-chain/.venv/lib/python3.9/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/Users/apple/work/x/ai-chain/.venv/lib/python3.9/site-packages/elasticsearch/_sync/client/__init__.py", line 3798, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/Users/apple/work/x/ai-chain/.venv/lib/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'runtime error')
```

**Comment by longgui0318** [comment]
This is the way I called the save, so, I made sure the index_name was the same and checked it on kibana
```    
    elastic_vector_search = ElasticVectorSearch(
        elasticsearch_url="http://192.168.1.2:9200",
        index_name="test20222",
        embedding=embeddings
    )
    elastic_vector_search.add_documents(docs);
```

**Comment by longgui0318** [comment]
Determine the problem, when using from_documents to build, and then use ElasticVectorSearch to build the object is normally accessible. But if we directly use ElasticVectorSearch to build the object and then add the content by way of add_documents, we will get an error when similarity_search

**Comment by longgui0318** [comment]
The difference is in this line of code

```
client.indices.create(index=index_name, mappings=mapping)
```

**Comment by longgui0318** [comment]
@sergerdn  

```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.document_loaders import UnstructuredWordDocumentLoader
from langchain.vectorstores import ElasticVectorSearch

if __name__ == "__main__":

    loader = UnstructuredWordDocumentLoader("test.docx",mode="elements")
    data = loader.load()
    text_spitter = CharacterTextSplitter(chunk_size=1000,chunk_overlap=0)
    docs = text_spitter.split_documents(data)
    embeddings = OpenAIEmbeddings()
    ## Case 1 start :this code is ok
    elastic_vector_search = ElasticVectorSearch.from_documents(
        docs,
        embedding=embeddings,
        elasticsearch_url="http://192.168.1.110:9200"        
    )
    ## Case 1 END
    searchResult = elastic_vector_search.similarity_search("What are the characteristics of sharks")
    ## Case 2 start:this code is error,Data saved successfully, but query has exceptions
    elastic_vector_search = ElasticVectorSearch(
        elasticsearch_url="http://192.168.1.110:9200",
        index_name="test20222",
        embedding=embeddings
    )
    elastic_vector_search.add_documents(docs)
    searchResult = elastic_vector_search.similarity_search("What are the characteristics of sharks")
    ## Case 2 END

```

**Comment by longgui0318** [comment]
tks

**Comment by longgui0318** [comment]
@sergerdn I think it may be that the information I gave is not accurate enough
```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.document_loaders import UnstructuredWordDocumentLoader
from langchain.vectorstores import ElasticVectorSearch

if __name__ == "__main__":

    loader = UnstructuredWordDocumentLoader("test.docx",mode="elements")
    data = loader.load()
    text_spitter = CharacterTextSplitter(chunk_size=1000,chunk_overlap=0)
    docs = text_spitter.split_documents(data)
    embeddings = OpenAIEmbeddings()
    searchResult = elastic_vector_search.similarity_search("What are the characteristics of sharks")
    ## Please note that test20222 was not created before this
    ## this code is error,Data saved successfully
    elastic_vector_search = ElasticVectorSearch(
        elasticsearch_url="http://192.168.1.110:9200",
        index_name="test20222",
        embedding=embeddings
    )
    ## Only now is the documents added
    elastic_vector_search.add_documents(docs)
    ## query has exceptions 'search_phase_execution_exceptionm'.Because of this approach, no client.indices.create(index=index_name, mappings=mapping) has been executed before add_documents
    searchResult = elastic_vector_search.similarity_search("What are the characteristics of sharks")
```

**Comment by longgui0318** [comment]
No, it was executed after adding the data and confirming that kibana saw the data, so I guess some key data initialization was missing that caused the inconsistency between the two structures

**Comment by carcaussa** [comment]
hi, I'm using version 0.0.186 and having this error, apparently I'm experiencing the same mapping issue, do you know how can I know when this is merged and included in a release of langchain?
Thank you very much

**Comment by Baro1502** [comment]
Hi, I am currently using version 0.0.248 and I still encounter this issue. Is there any way that I can address this? Thank you

**Comment by luccafabro** [comment]
@Baro1502 try create your index with this structure before inserts
PUT /your_index
{
  "mappings": {
    "properties": {
      "metadata": {
        "properties": {
          "source": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      },
      "text": {
        "type": "text"
      },
      "vector": {
        "type": "dense_vector",
        "dims": 1536
      }
    }
  }
}

**Comment by rizwanalvi1** [comment]
in my case, it happened when I used different embedding models for storing and retrieving/searching.
I was using OpenAIEmbeddings() for storing and by mistake using instructor-large for searching

hope this feedback would be of some use as well.
