### ISSUE TITLE
Error when creating HuggingFaceEmbeddings with chatglm-6b model

### ISSUE THREAD

**Issue by chenchun0629** [hwchase17/langchain#2710]
When I create `embeddings = HuggingFaceEmbeddings(model_name='THUDM/chatglm-6b')`

I get an error message: 
```
ValueError: Loading THUDM/chatglm-6b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.
```

How can I fix it?

python env:

```
python version: Python 3.8.10

transformers                   4.27.4
langchain                      0.0.136 
```

**Comment by rchanggogogo** [comment]
i think transformers is not support the model yet

**Comment by huangjiaheng** [comment]
> When I create `embeddings = HuggingFaceEmbeddings(model_name='THUDM/chatglm-6b')`
> 
> I get an error message:
> 
> ```
> ValueError: Loading THUDM/chatglm-6b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.
> ```
> 
> How can I fix it?
> 
> python env:
> 
> ```
> python version: Python 3.8.10
> 
> transformers                   4.27.4
> langchain                      0.0.136 
> ```

hello，你可以试下langchain-chatglm这个框架。我最近也想使用langchain把chatglm serving起来。
langchain-chatglm这个框架做demo可以，但是用来做serving，太慢了。可以多交流。

**Comment by huangjiaheng** [comment]
> 

他的这个embedding应该指的是将句子embedding的，chatglm是生成模型，应该搞不了这个吧

**Comment by russellballestrini** [comment]
This will allow you to download the models but it will throw an error later on about the argument already existing...

```
from langchain import HuggingFacePipeline

llm = HuggingFacePipeline.from_model_id(model_id="mosaicml/mpt-7b-chat", task="text-generation", model_kwargs={"temperature":0.1, "trust_remote_code":True})

from langchain import PromptTemplate,  LLMChain

template = """Question: {question}

Answer: Let's think step by step."""
prompt = PromptTemplate(template=template, input_variables=["question"])

llm_chain = LLMChain(prompt=prompt, llm=llm)

question = "What is electroencephalography?"

print(llm_chain.run(question))
```

```
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:07<00:00, 33.72s/it]
Traceback (most recent call last):
  File "/Users/russellballestrini/git/flaskchat/lang_chain8.py", line 4, in <module>
    llm = HuggingFacePipeline.from_model_id(model_id="mosaicml/mpt-7b-chat", task="text-generation", model_kwargs={"temperature":0.1, "trust_remote_code": True})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/russellballestrini/git/flaskchat/env/lib/python3.11/site-packages/langchain/llms/huggingface_pipeline.py", line 118, in from_model_id
    pipeline = hf_pipeline(
               ^^^^^^^^^^^^
  File "/Users/russellballestrini/git/flaskchat/env/lib/python3.11/site-packages/transformers/pipelines/__init__.py", line 779, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transformers.pipelines.base.infer_framework_load_model() got multiple values for keyword argument 'trust_remote_code'
```

**Comment by kool99988** [comment]
It is a good model, hope to see this feature soon
