### ISSUE TITLE
"substring not found" on every user suggestion

### ISSUE THREAD

**Issue by hanskraut31312312** [hwchase17/langchain#2756]
"substring not found" on every user input :(

Auto-GPT wont react to it. But the  "do nothing sickness"  from yesterday work again. (removed the do nothing command temporarily)

NEXT ACTION:  COMMAND = list_agents ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for AI_GPT_8...
Input:Whenever i give userfeedback there is a error and you dont seem to react to it. Please fix.
SYSTEM:  Human feedback: Whenever i give userfeedback there is a error and you dont seem to react to it. Please fix.
Error:
 Traceback (most recent call last): File "scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "C:\Programming\Auto-GPT_AI_8\scripts\json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found
NEXT ACTION:  COMMAND = Error: ARGUMENTS = substring not found

**Comment by hanskraut31312312** [comment]
Still having "substring not found" on every user input :(
