### ISSUE TITLE
class RequestsGetToolWithParsing(BaseRequestsTool, BaseTool):   File "langchain/agents/agent_toolkits/openapi/planner.py", line 48, in RequestsGetToolWithParsing

### ISSUE THREAD

**Issue by nuhmanpk** [hwchase17/langchain#2758]
`from langchain.agents.agent_toolkits.openapi import planner`

_Traceback (most recent call last):
  File "/app.py", line 12, in <module>
    from langchain.agents.agent_toolkits.openapi import planner
  File ".venv/lib/python3.10/sitepackages/langchain/agents/agent_toolkits/openapi/planner.py", line 43, in <module>
    class RequestsGetToolWithParsing(BaseRequestsTool, BaseTool):
  File ".venv/lib/python3.10/site-packages/langchain/agents/agent_toolkits/openapi/planner.py", line 48, in RequestsGetToolWithParsing
    llm=OpenAI(),
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)_

**Comment by nuhman-bititude** [comment]
_Probably I missed_ 
`export OPENAI_API_KEY=""`

**Comment by nuhmanpk** [comment]
Probably I missed 
`export OPENAI_API_KEY=`
