### ISSUE TITLE
Weaviate setup in docs is broken 

### ISSUE THREAD

**Issue by ashemag** [hwchase17/langchain#2820]
https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/weaviate.html

It doesn't look like `embeddings` var is used. This code fails on: 

```
======================================================================
ERROR: test_weaviate_setup (__main__.TestVectorStores)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_vectorstores.py", line 50, in test_weaviate_setup
    client.schema.create(schema)
  File "/Users/ashemagalhaes/opt/miniconda3/envs/hearth-modeling/lib/python3.8/site-packages/weaviate/schema/crud_schema.py", line 128, in create
    self._create_classes_with_primitives(loaded_schema["classes"])
  File "/Users/ashemagalhaes/opt/miniconda3/envs/hearth-modeling/lib/python3.8/site-packages/weaviate/schema/crud_schema.py", line 723, in _create_classes_with_primitives
    self._create_class_with_primitives(weaviate_class)
  File "/Users/ashemagalhaes/opt/miniconda3/envs/hearth-modeling/lib/python3.8/site-packages/weaviate/schema/crud_schema.py", line 708, in _create_class_with_primitives
    raise UnexpectedStatusCodeException("Create class", response)
weaviate.exceptions.UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': "module 'text2vec-openai': unsupported version 002"}]}.

----------------------------------------------------------------------
Ran 1 test in 0.564s

FAILED (errors=1)
sys:1: ResourceW
```

**Comment by bobvanluijt** [comment]
cc: @hsm207

**Comment by manubamba** [comment]
It worked for me by using this:
```
      "vectorizer": "text2vec-openai",
      "moduleConfig": {
          "text2vec-openai": {
          "model": "ada",
          "modelVersion": "002",
          "type": "text"
          }
      },

**Comment by hsm207** [comment]
@ashemag @manubamba we recently updated that [notebook example.](https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/weaviate.html) You don't actually need to set up weaviate with a vectorizer if using using it langchain because you can use the `embeddings` object.
