### ISSUE TITLE
Fix "validation errors for Batch" when call qdrant.add_texts

### ISSUE THREAD

**Issue by wangyumu** [hwchase17/langchain#2837]
### Description
`qdrant.add_texts` always failed 

### Steps to repreduce
Try add texts to qdrant like this :  
```python
import qdrant_client
client = qdrant_client.QdrantClient("localhost", port=6333)
qdrant = Qdrant(
    client=client, collection_name=COLLECTION_NAME, 
    embedding_function=embeddings.embed_documents
)
...
qdrant.add_texts( texts = [doc.page_content for doc in docs], metadatas = [doc.metadata for doc in docs])
```
and it will come out with error:
```
Traceback (most recent call last):
  File "build_vector_db.py", line 50, in <module>
    qdrant.add_texts( texts = [doc.page_content for doc in docs], metadatas = [doc.metadata for doc in docs])
  File "/usr/local/lib/python3.8/dist-packages/langchain/vectorstores/qdrant.py", line 81, in add_texts
    points=rest.Batch(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 732 validation errors for Batch
vectors -> 0 -> 0
  value is not a valid float (type=type_error.float)
vectors -> 0 -> 1
  value is not a valid float (type=type_error.float)
vectors -> 0 -> 2
  value is not a valid float (type=type_error.float)
vectors -> 0 -> 3
  value is not a valid float (type=type_error.float)
....
```

I think we may update the line (keep the same logic with `from_texts` which works fine):
``` python
vectors=[self.embedding_function(text) for text in texts],
```
to
``` python
vectors=self.embedding_function(texts)
```
I will make a PR for it

**Comment by wangyumu** [comment]
something wrong in my code:

Should change
```
qdrant = Qdrant(
    client=client, collection_name=COLLECTION_NAME, 
    embedding_function=embeddings.embed_documents
)
```
To
```
qdrant = Qdrant(
    client=client, collection_name=COLLECTION_NAME, 
    embedding_function=embeddings.embed_query
)
```

**Comment by waivey** [comment]
If you get here and wonder _why_ changing from `embed_documents` to `embed_query` worked, it's in the docs on [text embedding models](https://python.langchain.com/docs/integrations/text_embedding/huggingfacehub):

`embed_documents` expects a list of strings, and returns a list of embedding's 
`embed_query` expects a string and returns one embedding

Qdrant expects the upserted vector values to be one set of embeddings, unless you're batch uploading, but then all values added need to be lists of those values ([again see docs](https://qdrant.tech/documentation/concepts/points/#upload-points))
