### ISSUE TITLE
[Feature Request] BunJs Support 

### ISSUE THREAD

**Issue by LuisMalhadas** [hwchase17/langchain#2888]
I have been working with [BunJS](https://bun.sh) runtime and decided to try langchain with it.
I also noted in documentation that there are some supported runtimes...
It seems that it is not fully compatible with Bun... It imports, instantiates the model, but doesn't execute it.
Am I doing something wrong?
```javascript
import { OpenAI } from "langchain/llms/openai";
console.log("imported");
const model = new OpenAI({ openAIApiKey: "sk-...", temperature: 0.7 });
console.log("model created")
const res = await model.call(
    "What would be a good company name a company that makes colorful socks?"
);
console.log(res);
```
Running the example:
```shell
% bun index.ts
imported
model created
38 |         const PQueue = "default" in PQueueMod ? PQueueMod.default : PQueueMod;
39 |         this.queue = new PQueue({ concurrency: this.maxConcurrency });
40 |     }
41 |     // eslint-disable-next-line @typescript-eslint/no-explicit-any
42 |     call(callable, ...args) {
43 |         return this.queue.add(() => pRetry(() => callable(...args).catch((error) => {
                   ^
TypeError: undefined is not a function (near '...this.queue.add...')
      at call (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/util/async_caller.js:43:15)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:312:15
      at completionWithRetry (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:300:30)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:270:24
      at _generate (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:204:20)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/base.js:43:27
```

**Comment by homanp** [comment]
This should be posted in the langchainjs repo: https://github.com/hwchase17/langchainjs

Also check out this discussion: https://github.com/hwchase17/langchainjs/discussions/152

**Comment by LuisMalhadas** [comment]
You are right, sorry.
I also took a look at the discussion, voted, and upvoted the bun request comment. :)
Saw that someone already claimed support for bun, but not all parts of langchain, I guess.
Anyway, I'll close this and repost on the proper rep.
