### ISSUE TITLE
Langchain not working on Lambda from 0.0.128

### ISSUE THREAD

**Issue by Eyon42** [hwchase17/langchain#3097]
Trying to import langchain 0.0.128 and up in AWS Lambda (Using serverless framework) fails with this:

I suspect that this is the PR that causes the issue.

Maybe the __version__ line should be wrapped in a try catch in case the code is ran on an environment where the metadata for packages is not available, as it happens with serverless python requirements.

https://github.com/hwchase17/langchain/pull/2221

```
[ERROR] PackageNotFoundError: No package metadata was found for langchain
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/s_event_webhook.py", line 25, in error_handler
    raise e
  File "/var/task/s_event_webhook.py", line 20, in <module>
    user_handler = serverless_sdk.get_user_handler('endpoints.event_webhook.handler')
  File "/var/task/serverless_sdk/__init__.py", line 56, in get_user_handler
    user_module = import_module(user_module_name)
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/endpoints/event_webhook.py", line 8, in <module>
    from chatlib.agent import handle_event
  File "/var/task/chatlib/agent.py", line 7, in <module>
    from langchain import LLMChain
  File "/var/task/langchain/__init__.py", line 58, in <module>
    __version__ = metadata.version(__package__)
  File "/var/lang/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/var/lang/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/var/lang/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
```

**Comment by Eyon42** [comment]
Solved by #3107
