### ISSUE TITLE
Bug in saving agent since version v0.0.142

### ISSUE THREAD

**Issue by Lothiraldan** [hwchase17/langchain#3217]
I've been investigating an error when running agent based example with the Comet callback when trying to save the agent to disk.

I have been able to narrow the bug down to the following reproduction script:

```python
import os
from datetime import datetime

import langchain
from langchain.agents import initialize_agent, load_tools
from langchain.callbacks import CometCallbackHandler, StdOutCallbackHandler
from langchain.callbacks.base import CallbackManager
from langchain.llms import OpenAI

llm = OpenAI(temperature=0.9, verbose=True)

tools = load_tools(["serpapi", "llm-math"], llm=llm)
agent = initialize_agent(
    tools,
    llm,
    agent="zero-shot-react-description",
    verbose=True,
)

agent.save_agent("/tmp/langchain.json")
```

Which fails with the following Exception:
```python
Traceback (most recent call last):
  File "/home/lothiraldan/project/cometml/langchain/docs/ecosystem/test_comet_ml_3.py", line 39, in <module>
    agent.save_agent("/tmp/langchain.json")
  File "/home/lothiraldan/project/cometml/langchain/langchain/agents/agent.py", line 599, in save_agent
    return self.agent.save(file_path)
  File "/home/lothiraldan/project/cometml/langchain/langchain/agents/agent.py", line 145, in save
    agent_dict = self.dict()
  File "/home/lothiraldan/project/cometml/langchain/langchain/agents/agent.py", line 119, in dict
    _dict = super().dict()
  File "pydantic/main.py", line 435, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 833, in _iter
  File "pydantic/main.py", line 708, in pydantic.main.BaseModel._get_value
  File "/home/lothiraldan/project/cometml/langchain/langchain/schema.py", line 381, in dict
    output_parser_dict["_type"] = self._type
  File "/home/lothiraldan/project/cometml/langchain/langchain/schema.py", line 376, in _type
    raise NotImplementedError
NotImplementedError
```

Using that reproduction script, I was able to run git bisect that identified the following commit as the probable cause: https://github.com/hwchase17/langchain/commit/e12e00df12c6830cd267df18e96fda1ef8df6c7a

I am not sure of the scope of that issue and if it's mean that no agent can be exported to JSON or YAML since then.

Let me know if I can help more on debugging that issue.

**Comment by kennethleungty** [comment]
Am facing this issue as well, glad that you brought this up, I had thought it was something wrong on my end

**Comment by cnhhoang850** [comment]
I remove the @property from schema.py for BaseOutputParser and the _agent_type pass correctly to Basemodel.dict

**Comment by vowelparrot** [comment]
Looks like the bug is that the MRKLOutputParser lacks the `_type()` arg. The type argument is currently used to decide how to re-load the parser. I'll add a separate fix

**Comment by mzhadigerov** [comment]
any updates on this? I'm facing the same error
