### ISSUE TITLE
Why is this implementation of vectorstore not working?

### ISSUE THREAD

**Issue by Ryangr0** [hwchase17/langchain#3286]
I'm not super in the know about python, so maybe there's just something that happens that I don't understand, but consider the following:

```
ryan_memories = GenerativeAgentMemory(
    llm=LLM,
    memory_retriever=create_new_memory_retriever(),
    verbose=True,
    reflection_threshold=8
)

ryan = GenerativeAgent(
    name="Ryan", 
    age=28,
    traits="experimental, hopeful, programmer",
    status="Executing the task",
    memory=ryan_memories,
    llm=LLM,
    daily_summaries = [
        "Just woke up, about to start working."
    ],
)

def create_new_memory_retriever():
    """Create a new vector store retriever unique to the agent."""

    client = weaviate.Client(
        url=WEAVIATE_HOST,
        additional_headers={"X-OpenAI-Api-Key": os.getenv("OPENAI_API_KEY")}
    )
    vectorstore = Weaviate(client, "Paragraph", "content")

    return TimeWeightedVectorStoreRetriever(vectorstore=vectorstore, other_score_keys=["importance"], k=15)    
```

The traceback:
```
Traceback (most recent call last):
  File "/app/test.py", line 80, in <module>
    print(ryan.get_summary())
          ^^^^^^^^^^^^^^^^^^
  File "/app/agents/GenerativeAgent.py", line 206, in get_summary
    self.summary = self._compute_agent_summary()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agents/GenerativeAgent.py", line 193, in _compute_agent_summary
    .run(name=self.name, queries=[f"{self.name}'s core characteristics"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
           ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 106, in __call__
    inputs = self.prep_inputs(inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 193, in prep_inputs
    external_context = self.memory.load_memory_variables(inputs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agents/memory.py", line 187, in load_memory_variables
    relevant_memories = [
                        ^
  File "/app/agents/memory.py", line 188, in <listcomp>
    mem for query in queries for mem in self.fetch_memories(query)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agents/memory.py", line 151, in fetch_memories
    return self.memory_retriever.get_relevant_documents(observation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/retrievers/time_weighted_retriever.py", line 90, in get_relevant_documents
    docs_and_scores.update(self.get_salient_docs(query))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/retrievers/time_weighted_retriever.py", line 72, in get_salient_docs
    docs_and_scores = self.vectorstore.similarity_search_with_relevance_scores(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 94, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 117, in _similarity_search_with_relevance_scores
    raise NotImplementedError
NotImplementedError
```

When I go to that file, I indeed see that the base class doesn't have an implementation, but it should be using the vectorstore I created, and therefore the implementation of that class, not the base implementation?

What am I missing here?

**Comment by Ryangr0** [comment]
It looks like the time weighted retriever, using the weaviate client vectorstore is just calling a method it expects to be there, but it's not. I'll look into this and try to come up with a solution.

**Comment by michaelnagy** [comment]
I'm also facing this issue when trying to call "similarity_search_with_relevance_scores" method.

**Comment by diostam** [comment]
same here, I get `NotImplementedError` when trying to run a retriever with search_type = "similarity_score_threshold"

**Comment by jihopark** [comment]
Same here for using Chroma DB! It seems like Python code is calling langchain/vectorstores/base.py instead of the inherited class of _similarity_search_with_relevance_scores.

**Comment by schwarbf** [comment]
I have the same issue for Pinecone when trying to call `max_marginal_relevance_search`.

**Comment by matif** [comment]
I have the same issue when using the async Pinecone.afrom_documents method.

**Comment by wissam-natex** [comment]
You need to update langchain, that's all. 

This method had this 'placeholder' NotImplementedError for a while. 
A few versions down the line it was turned into an actual function that does something, and they removed the line "raise NotImplementedError.

**Comment by younes-io** [comment]
> You need to update langchain, that's all.
> 
> This method had this 'placeholder' NotImplementedError for a while. A few versions down the line it was turned into an actual function that does something, and they removed the line "raise NotImplementedError".

I'm using LangChain 0.0.327 and I face the same issue..
