### ISSUE TITLE
ChatGPT Plugin sample code cannot be executed

### ISSUE THREAD

**Issue by k-nasa** [hwchase17/langchain#3577]
## Description

ref: https://python.langchain.com/en/latest/modules/agents/tools/examples/chatgpt_plugins.html

Thanks for the great tool.

I'm trying ChatGPT Plugin.
I get an error when I run the sample code in the document.

It looks like it's caused by single quotes.

### output

```
> Entering new AgentExecutor chain...
I need to use the Klarna Shopping API to search for available t shirts.
Action: KlarnaProducts
Action Input: None
Observation: Usage Guide: Assistant uses the Klarna plugin to get relevant product suggestions for any shopping or product discovery purpose. Assistant will reply with the following 3 paragraphs 1) Search Results 2) Product Comparison of the Search Results 3) Followup Questions. The first paragraph contains a list of the products with their attributes listed clearly and concisely as bullet points under the product, together with a link to the product and an explanation. Links will always be returned and should be shown to the user. The second paragraph compares the results returned in a summary sentence starting with "In summary". Assistant comparisons consider only the most important features of the products that will help them fit the users request, and each product mention is brief, short and concise. In the third paragraph assistant always asks helpful follow-up questions and end with a question mark. When assistant is asking a follow-up question, it uses it's product expertise to provide information pertaining to the subject of the user's request that may guide them in their search for the right product.

OpenAPI Spec: {'openapi': '3.0.1', 'info': {'version': 'v0', 'title': 'Open AI Klarna product Api'}, 'servers': [{'url': 'https://www.klarna.com/us/shopping'}], 'tags': [{'name': 'open-ai-product-endpoint', 'description': 'Open AI Product Endpoint. Query for products.'}], 'paths': {'/public/openai/v0/products': {'get': {'tags': ['open-ai-product-endpoint'], 'summary': 'API for fetching Klarna product information', 'operationId': 'productsUsingGET', 'parameters': [{'name': 'q', 'in': 'query', 'description': "A precise query that matches one very small category or product that needs to be searched for to find the products the user is looking for. If the user explicitly stated what they want, use that as a query. The query is as specific as possible to the product name or category mentioned by the user in its singular form, and don't contain any clarifiers like latest, newest, cheapest, budget, premium, expensive or similar. The query is always taken from the latest topic, if there is a new topic a new query is started.", 'required': True, 'schema': {'type': 'string'}}, {'name': 'size', 'in': 'query', 'description': 'number of products returned', 'required': False, 'schema': {'type': 'integer'}}, {'name': 'min_price', 'in': 'query', 'description': "(Optional) Minimum price in local currency for the product searched for. Either explicitly stated by the user or implicitly inferred from a combination of the user's request and the kind of product searched for.", 'required': False, 'schema': {'type': 'integer'}}, {'name': 'max_price', 'in': 'query', 'description': "(Optional) Maximum price in local currency for the product searched for. Either explicitly stated by the user or implicitly inferred from a combination of the user's request and the kind of product searched for.", 'required': False, 'schema': {'type': 'integer'}}], 'responses': {'200': {'description': 'Products found', 'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ProductResponse'}}}}, '503': {'description': 'one or more services are unavailable'}}, 'deprecated': False}}}, 'components': {'schemas': {'Product': {'type': 'object', 'properties': {'attributes': {'type': 'array', 'items': {'type': 'string'}}, 'name': {'type': 'string'}, 'price': {'type': 'string'}, 'url': {'type': 'string'}}, 'title': 'Product'}, 'ProductResponse': {'type': 'object', 'properties': {'products': {'type': 'array', 'items': {'$ref': '#/components/schemas/Product'}}}, 'title': 'ProductResponse'}}}}
Thought:I need to use the Klarna Shopping API to search for available t shirts.
Action: requests_get
Action Input: 'https://www.klarna.com/us/shopping/public/openai/v0/products?q=t%20shirts&size=10'Traceback (most recent call last):
  File "test.py", line 11, in <module>
    agent_chain.run("what t shirts are available in klarna?")
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/agents/agent.py", line 792, in _call
    next_step_output = self._take_next_step(
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/agents/agent.py", line 695, in _take_next_step
    observation = tool.run(
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/tools/base.py", line 184, in run
    raise e
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/tools/base.py", line 181, in run
    observation = self._run(*tool_args, **tool_kwargs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/tools/requests/tool.py", line 31, in _run
    return self.requests_wrapper.get(url)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/requests.py", line 125, in get
    return self.requests.get(url, **kwargs).text
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/langchain/requests.py", line 28, in get
    return requests.get(url, headers=self.headers, **kwargs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/requests/sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "/Users/asan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "'https://www.klarna.com/us/shopping/public/openai/v0/products?q=t%20shirts&size=10'"
```

### source code 

```python
from langchain.chat_models import ChatOpenAI
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
from langchain.tools import AIPluginTool
tool = AIPluginTool.from_plugin_url("https://www.klarna.com/.well-known/ai-plugin.json")
llm = ChatOpenAI(temperature=0)
tools = load_tools(["requests_all"] )
tools += [tool]

agent_chain = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
agent_chain.run("what t shirts are available in klarna?")
```

### versions

- ptyhon: 3.8.12
- langchain: '0.0.149'

<details><summary>Details</summary>
<p>

```sh
~/lab/wantedly/visit-machine-learning /langchain_plugin - ⚑ ✚ …  nsmryk/add_langchain_plugin  - SIGHUP
:( % python --version
Python 3.8.12

~/lab/wantedly/visit-machine-learning /langchain_plugin - ⚑ ✚ …  nsmryk/add_langchain_plugin
:) % python
Python 3.8.12 (default, Mar 30 2022, 16:26:57)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import langchain
lang>>> langchain.__version__
'0.0.149'
>>>
```

</p>
</details>

**Comment by k-nasa** [comment]
oops. It was resolved this. https://github.com/hwchase17/langchain/pull/3563
