### ISSUE TITLE
`LLMMatchChain` ValueError encountered when using `ZeroShotAgent`

### ISSUE THREAD

**Issue by agola11** [hwchase17/langchain#370]
```
# Load the tool configs that are needed.
from langchain import LLMMathChain, SerpAPIWrapper
llm = OpenAI(temperature=0)
search = SerpAPIWrapper()
llm_math_chain = LLMMathChain(llm=llm, verbose=True)
tools = [
    Tool(
        name = "Search",
        func=search.run,
        description="useful for when you need to answer questions about current events"
    ),
    Tool(
        name="Calculator",
        func=llm_math_chain.run,
        description="useful for when you need to answer questions about math"
    )
]

agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
agent.run("Who won the US Open men's tennis final in 2022? What is the next prime number after his age?")
```

Produces:
```> Entering new ZeroShotAgent chain...
Who won the US Open men's tennis final in 2022? What is the next prime number after his age?
Thought: I need to find out who won the US Open and then calculate the next prime number
Action: Search
Action Input: "US Open men's tennis final 2022"
Observation: Spain's Carlos Alcaraz, 19, defeated Casper Ruud in the 2022 US Open men's singles final to earn his first Grand Slam title.
Thought: I need to calculate the next prime number
Action: Calculator
Action Input: 19

> Entering new LLMMathChain chain...
19 + 4
Answer: 23Traceback (most recent call last):
  File "/Users/ankushgola/Code/langchain/tests/agent_test.py", line 70, in <module>
    main()
  File "/Users/ankushgola/Code/langchain/tests/agent_test.py", line 65, in main
    agent.run("Who won the US Open men's tennis final in 2022? What is the next prime number after his age?")
  File "/Users/ankushgola/Code/langchain/langchain/chains/base.py", line 134, in run
    return self({self.input_keys[0]: text})[self.output_keys[0]]
  File "/Users/ankushgola/Code/langchain/langchain/chains/base.py", line 107, in __call__
    outputs = self._call(inputs)
  File "/Users/ankushgola/Code/langchain/langchain/agents/agent.py", line 150, in _call
    observation = chain(output.tool_input)
  File "/Users/ankushgola/Code/langchain/langchain/chains/base.py", line 134, in run
    return self({self.input_keys[0]: text})[self.output_keys[0]]
  File "/Users/ankushgola/Code/langchain/langchain/chains/base.py", line 107, in __call__
    outputs = self._call(inputs)
  File "/Users/ankushgola/Code/langchain/langchain/chains/llm_math/base.py", line 70, in _call
    raise ValueError(f"unknown format from LLM: {t}")
ValueError: unknown format from LLM: + 4
Answer: 23
```

Very interesting that the answer is actually correct. The problem is that the output from the calculator is:
```
 ' + 4
Answer: 23'
```

`ValueError` is being thrown bc output of Calculator doesn't being with `'Answer:'`

Can repro with another input (also involving prime numbers):
```
agent.run("Who won the US Open men's tennis final in 2019? What is the next prime number after his age?")
```

In this case, the output from the calculator is
```
'?
Answer: 37'
```

Again, interesting that answer is actually correct.

**Comment by dreamteam-z** [comment]
same issue here

**Comment by hwchase17** [comment]
@agola11 @dreamteam-z i opened up the above pr for hopefully a simple fix
