### ISSUE TITLE
langchain.schema.OutputParserException: Could not parse LLM output: `

### ISSUE THREAD

**Issue by fbettag** [hwchase17/langchain#3750]
Hey there,

thanks for langchain! It's super awesome! 👍 

I am currently trying to write a simple REST API but i am getting somewhat random errors. Sometimes (about 1 in 15 runs) it's this:

``` 
% python3 app.py "Who won the superbowl the year justin bieber was born?"
llama.cpp: loading model from /Users/myadmin/dalai/llama/models/13B/13b-ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  =  400.00 MB
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Answer the following questions as best you can. You have access to the following tools:

Google Search: A wrapper around Google Search. Useful for when you need to answer questions about current events. Input should be a search query.
Wikipedia: A wrapper around Wikipedia. Useful for when you need to answer general questions about people, places, companies, historical events, or other subjects. Input should be a search query.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Google Search, Wikipedia]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
{agent_scratchpad}
-- Serving request for input: Who won the superbowl the year justin bieber was born?


> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/Users/myadmin/lc-serve/app.py", line 54, in <module>
    ask(sys.argv[1])
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/lcserve/backend/decorators.py", line 14, in sync_wrapper
    return func(*args, **kwargs)
  File "/Users/myadmin/lc-serve/app.py", line 47, in ask
    return agent_executor.run(input)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 796, in _call
    next_step_output = self._take_next_step(
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 676, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 385, in plan
    return self.output_parser.parse(full_output)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/mrkl/output_parser.py", line 26, in parse
    raise OutputParserException(f"Could not parse LLM output: `{text}`")
langchain.schema.OutputParserException: Could not parse LLM output: `
Thought: I don't know who won that year... or what happened in the next 3 years.

Action: Google Search

Google Search: Super Bowl`
``` 

The script is as follows:
```python
# app.py

#model = "/Users/myadmin/dalai/"
model = "/Users/myadmin/dalai/llama/models/13B/13b-ggml-model-q4_0.bin"
#model = "/Users/myadmin/dalai/llama/models/13B/ggml-vic13b-q5_1.bin"
#model = "/Users/myadmin/dalai/alpaca/models/30B/ggml-model-q4_0.bin"

import sys, os
os.environ["GOOGLE_CSE_ID"] = "xyz"
os.environ["GOOGLE_API_KEY"] = "xyz"

from langchain import LLMChain
from langchain.llms import LlamaCpp
from langchain.agents import AgentExecutor, Tool, ZeroShotAgent, load_tools

from lcserve import serving


prefix = """Answer the following questions as best you can. You have access to the following tools:"""
#suffix = """Begin! Remember to speak as a pirate when giving your final answer. Use lots of "Args"
suffix = """Begin!

Question: {input}
{agent_scratchpad}"""

llm = LlamaCpp(model_path=model, verbose=True)
tools = load_tools(["google-search", "wikipedia"], llm=llm)
prompt = ZeroShotAgent.create_prompt(
	tools,
	prefix=prefix,
	suffix=suffix,
	input_variables=["input", "agent_scratchpad"],
)

print(prompt.template)

llm_chain = LLMChain(llm=llm, prompt=prompt)
tool_names = [tool.name for tool in tools]
agent = ZeroShotAgent(llm_chain=llm_chain, allowed_tools=tool_names)

agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True)


@serving
def ask(input: str) -> str:
	print("-- Serving request for input: %s" % input)
	return agent_executor.run(input)


if __name__ == "__main__":
	if len(sys.argv) == 1:
		ask('How many people live in canada as of 2023?')
	else:
		ask(sys.argv[1])
```

Not quite sure what i'm doing wrong here, or if it's just purely a random thing i should just catch?

Thank you very much in advance!

**Comment by Hamas-ur-Rehman** [comment]
@fbettag I believe a workaround might be to try this 
```
@serving
def ask(input: str) -> str:
	print("-- Serving request for input: %s" % input)
        try:
             response= agent_executor.run(input)
        except Exception as e:
             response = str(e)
             if response.startswith("Could not parse LLM output: `"):
                  response = response.removeprefix("Could not parse LLM output: `").removesuffix("`")
	return response

```
This is not perfect but it may give you an idea you can even try to run the query again and this time pass some instructions to it so it doesn't give that sort of answer

**Comment by fbettag** [comment]
> @fbettag I believe a workaround might be to try this
> 
> ```
> @serving
> def ask(input: str) -> str:
> 	print("-- Serving request for input: %s" % input)
>         try:
>              response= agent_executor.run(input)
>         except Exception as e:
>              response = str(e)
>              if response.startswith("Could not parse LLM output: `"):
>                   response = response.removeprefix("Could not parse LLM output: `").removesuffix("`")
> 	return response
> ```
> 
> This is not perfect but it may give you an idea you can even try to run the query again and this time pass some instructions to it so it doesn't give that sort of answer

Well i went as far as doing this

```
@serving
def ask(input: str) -> str:
	try:
		response = agent_executor.run(input)
	except Exception as e:
		response = str(e)
		if response.startswith("Could not parse LLM output: `"):
			response = response.removeprefix("Could not parse LLM output: `").removesuffix("`")
			return response
		else:
			response = "{\"error\": \"%s\"}" % str(e)
```

Now at least i get the "Thought" half way decently out of it.

I'd still like to understand the issue itself, is it that the model can't handle german prompts?

**Comment by Hamas-ur-Rehman** [comment]
well, I had the same issue while my prompts were in Greek this can occur when the LLM fails to follow the proper format and may give the answers slightly altered. One way is to keep telling the LLM to follow the correct pattern to answer. 

The method langchain is using is very prone to errors as this is a bad way to have a parser that would parse just based on the pattern only and raise an error if the response is not in the correct form.

Either you can have another LLM and ask it to parse and return the output from the given text which is a simple but slow solution another one would be to write your own parser and modify the one langchain provides to be robust and work if the pattern is not followed

**Comment by fbettag** [comment]
that makes so much sense. thank you!

**Comment by codysaint** [comment]
> check this, worked for me: https://python.langchain.com/en/latest/modules/agents/agent_executors/examples/handle_parsing_errors.html

This page is removed. Could you please provide correct link, if possible.

**Comment by jaceklaskowski** [comment]
https://python.langchain.com/docs/modules/agents/how_to/handle_parsing_errors ?
