### ISSUE TITLE
ValueError: Requested tokens exceed context window of 512

### ISSUE THREAD

**Issue by fbettag** [hwchase17/langchain#3751]
Hey guys,

the code is absolutely the same as https://github.com/hwchase17/langchain/issues/3750 but just with a german prompt.

The prompt justs asks for recommendations about things to do in Middle-Franconia (part of Germany).

```
% python3 app.py "Nenne mir 3 Ausflugsziele in Mittelfranken?"           
llama.cpp: loading model from /Users/myadmin/dalai/llama/models/13B/13b-ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  =  400.00 MB
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Answer the following questions as best you can. You have access to the following tools:

Google Search: A wrapper around Google Search. Useful for when you need to answer questions about current events. Input should be a search query.
Wikipedia: A wrapper around Wikipedia. Useful for when you need to answer general questions about people, places, companies, historical events, or other subjects. Input should be a search query.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Google Search, Wikipedia]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
{agent_scratchpad}
-- Serving request for input: Nenne mir 3 Ausflugsziele in Mittelfranken?


> Entering new AgentExecutor chain...
Thought: what to do
Action: Google Search
Google Search: "Ausflugsziele mittelfranken"
Results:
    - https://www.mittelfrankenschau.de/service/kultur/ausflüge-mitten-fuer-franken/
    - https://mw21.de/blog/flaechen/10-top-ausflugsziele-in-mittel-franken
    - http://www.m-frankfurt.de/ausflugsziele/
Action Input: "mittelfranken"
Observation: Google Search
Google Search: "Ausflugsziele mittelfranken"
Results:
    - https://www.mittelfrankenschau.de/service/kultur/ausflüge-mitten-fuer-franken/
    - https://mw21.de/blog/flaechen/10-top-ausflugsziele-in-mittel-franken
    - http://www.m-frankfurt.de/ausflugsziele/ is not a valid tool, try another one.
Thought:Traceback (most recent call last):
  File "/Users/myadmin/lc-serve/app.py", line 54, in <module>
    ask(sys.argv[1])
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/lcserve/backend/decorators.py", line 14, in sync_wrapper
    return func(*args, **kwargs)
  File "/Users/myadmin/lc-serve/app.py", line 47, in ask
    return agent_executor.run(input)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 796, in _call
    next_step_output = self._take_next_step(
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 676, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/agents/agent.py", line 384, in plan
    full_output = self.llm_chain.predict(**full_inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/base.py", line 324, in _generate
    text = self._call(prompt, stop=stop)
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/llamacpp.py", line 222, in _call
    for token in self.stream(prompt=prompt, stop=stop):
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/langchain/llms/llamacpp.py", line 268, in stream
    for chunk in result:
  File "/Users/myadmin/Library/Python/3.9/lib/python/site-packages/llama_cpp/llama.py", line 426, in _create_completion
    raise ValueError(
ValueError: Requested tokens exceed context window of 512
```

I am guessing (no idea really) that some of the search results might be too big, but i am also uncertain of how to use a TextSplitter in between the load_tools and google search result parsing.

Any ideas would be greatly appreciated!

Thanks in advance!

**Comment by InfinitySoftware-House** [comment]
Same here!

**Comment by fbettag** [comment]
thank you!

**Comment by InfinitySoftware-House** [comment]
Do your tools work? The observation step give me this error **"is not a valid tool, try another one."** with wikipedia tool

**Comment by fbettag** [comment]
i know that google works, i threw in wikipedia just for the kicks. Is there an easy way to test a specific tool, other than asking it to search with the specific tool?

**Comment by fbettag** [comment]
i'm gonna try them out in python real quick. but google i know works, wikipedia not so sure :)

after testing: wikipedia.run('HUNTER X HUNTER') returned the expected content.

**Comment by InfinitySoftware-House** [comment]
This is what I get from every tool I try to use...

`Thought: I must find out how many people live in Italy.
Action: Use Wikipedia search engine.
Action Input: "Italy"
Observation: Use Wikipedia search engine. is not a valid tool, try another one.
Thought:generate cache hit
 It's important to know which country the question refers to.
Action: Search for 'Italy' in Google.
Action Input: "Italy".
Observation: Search for 'Italy' in Google. is not a valid tool, try another one.
Thought:generate cache hit
 It's important to know which language we are using.
Action: Use requests to access Italian Wikipedia.
Action Input: "en"
Observation: Use requests to access Italian Wikipedia. is not a valid tool, try another one.
Thought:generate cache hit
 I need more precise input for the search query.
Action: Use Google to search for 'Italy' and 'population'.
Action Input: "Italy population".
Observation: Use Google to search for 'Italy' and 'population'. is not a valid tool, try another one.`

**Comment by InfinitySoftware-House** [comment]
I see that the action step give me this: `Action: I use requests to search 'Italy' on Google and visit its page.`, while it should only `Action: requests` or  `Action: wikipedia`.
Is there an error with the prompt template?

**Comment by fbettag** [comment]
Good question. Have you tried using the tool in the python repl?

**Comment by ErfolgreichCharismatisch** [comment]
/OFFTOPIC

> The prompt justs asks for recommendations about things to do in Middle-Franconia (part of Germany).

Da kann man gar nichts machen, da hilft auch Künstliche Intelligenz nicht weiter, wer da mal gelebt hat, weiß, wo es deprimierend ist.

**Comment by jlonge4** [comment]
> Find a possible solution:
> `LlamaCpp(model_path=model, verbose=True, n_ctx=2048)`
> Add **n_ctx=2048** to increase context length.
