### ISSUE TITLE
ValueError: Missing some input keys: {'input'}

### ISSUE THREAD

**Issue by ziadzee** [hwchase17/langchain#4673]
### System Info

I'm trying to make use of the sequential chaining functionality by chaining together two prompts like so:

```
# importing frameworks and such
import os
from apikey import apikey

import streamlit as st
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain, SimpleSequentialChain

os.environ["OPENAI_API_KEY"] = apikey

# Defning and building out our OOTB app framework via Streamlit
st.title("Medical GPT")
prompt = st.text_input("Enter your prompt here")

# Defining our prompt template
illness_template = PromptTemplate(
        input_variables=["condition"],
        template="Summarise the common symptoms for {condition}"
)

treatment_template = PromptTemplate(
        input_variables=["illness"],
        template="Summarise the treatment for this illness ILLNESS: {illness}"
)

# Defining our LLM and chains
llm = OpenAI(temperature=0.7)

illness_chain = LLMChain(llm=llm,
                       prompt=illness_template,
                       verbose=True)

treatment_chain = LLMChain(llm=llm,
                       prompt=treatment_template,
                       verbose=True)


sequential_chain = SimpleSequentialChain(chains=[illness_chain, treatment_chain])

# Return prompt output to frontend when a prompt is given
if prompt:
        response = sequential_chain.run(topic=prompt)
        st.write(response)
```

For some reason, it keeps throwing the error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/user/Langchain_hacking/app.py", line 43, in <module>
    response = sequential_chain.run(topic=prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 123, in __call__
    inputs = self.prep_inputs(inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 216, in prep_inputs
    self._validate_inputs(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 83, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'input'}
```

I'm not entirely sure why it keeps throwing up this error, as far as the documentation goes I'm calling `SimpleSequentialChain` correctly unless I'm missing something? 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
if prompt:
        response = sequential_chain.run(topic=prompt)
        st.write(response)
```

### Expected behavior

LLM output

**Comment by Data-drone** [comment]
How did you fix?

**Comment by jrxavier** [comment]
Having the same issue!

**Comment by meherjyothi** [comment]
Did anyone figure out the fix?
