### ISSUE TITLE
Issue: RetrievalQA is not working with AzureOpenAI LLM model

### ISSUE THREAD

**Issue by akshayghatiki311** [hwchase17/langchain#4966]
### Issue you'd like to raise.

I'm trying to query from my knowledge base in csv by creating embeddings.
I was able to do it with OpenAI LLM model. But when I'm trying with AzureOpenAI model, I'm getting an error.
I've checked the LLM object for both OpenAI modela and AzureOpenAI model, attributes are all same, but I'm getting below error.
I'm using text-embeddings-ada-002 for creating embeddings and text-davinci-003 for LLM model.
It would be great if someone can give me leads. Thanks in advance.

Error:
Traceback (most recent call last):
  File "C:\Users\akshay\Documents\GPT\azureLlmGPT.py", line 64, in <module>
    print(model.run(question))
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
           ^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\retrieval_qa\base.py", line 110, in _call
    answer = self.combine_documents_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 216, in run
    return self(kwargs)[self.output_keys[0]]
           ^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\combine_documents\base.py", line 75, in _call
    output, extra_return_dict = self.combine_docs(docs, **other_keys)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\combine_documents\map_reduce.py", line 139, in combine_docs
    results = self.llm_chain.apply(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\llm.py", line 118, in apply
    response = self.generate(input_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\base.py", line 140, in generate
    raise e
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\openai.py", line 297, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\openai.py", line 102, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\openai.py", line 100, in _completion_with_retry
    return llm.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\akshay\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found

**Comment by akshayghatiki311** [comment]
I've used model_kwargs and deployment_name instead of deployment and it working

**Comment by N-E-W-T-O-N** [comment]
Can you please tell me what is your API version.
If you are using before 2022-03-15-preview that will give you error
