### ISSUE TITLE
Issue: HuggingFaceEmbeddings can not take trust_remote_code argument

### ISSUE THREAD

**Issue by jackfrost1411** [hwchase17/langchain#6080]
### Issue you'd like to raise.

![image](https://github.com/hwchase17/langchain/assets/48760936/5400f6ca-d06b-49f0-a889-68f4e8e41598)

**Comment by damingerdai** [comment]
i also meet this issue

**Comment by damingerdai** [comment]
i fixed by this code:

```diff
from langchain.llms import HuggingFacePipeline
from langchain.memory.buffer import ConversationBufferMemory
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, AutoModelForSeq2SeqLM

local_llm = HuggingFacePipeline.from_model_id(
        model_id="chatglm-6b-int4",
        task="text-generation",
        model_kwargs={
            "temperature": 0, "max_length": 64,
+           "trust_remote_code": True
        },
    )
print(local_llm('What is the capital of France? '))
```

**Comment by AllenNing420** [comment]
> i fixed by this code:
> 
> ```diff
> from langchain.llms import HuggingFacePipeline
> from langchain.memory.buffer import ConversationBufferMemory
> from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, AutoModelForSeq2SeqLM
> 
> local_llm = HuggingFacePipeline.from_model_id(
>         model_id="chatglm-6b-int4",
>         task="text-generation",
>         model_kwargs={
>             "temperature": 0, "max_length": 64,
> +           "trust_remote_code": True
>         },
>     )
> print(local_llm('What is the capital of France? '))
> ```

I got this, any solutions?
`ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
`

**Comment by nbbaier** [comment]
The above solution doesn't work for `HuggingFaceEmbeddings`:

```py
from langchain.embeddings import HuggingFaceEmbeddings

model_name = "jinaai/jina-embeddings-v2-small-en"
model_kwargs = {"device": "cpu", "trust_remote_code": True}
encode_kwargs = {
    "normalize_embeddings": False,
}
hf = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)
text = "This is a test document."

res = hf.embed_query(text)

print(len(res))
```
Results in the following error:

```
Traceback (most recent call last):
  File "/Users/nbbaier/grubby-galaxy/main.py", line 9, in <module>
    hf = HuggingFaceEmbeddings(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbbaier/.pyenv/versions/3.11.0/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 66, in __init__
    self.client = sentence_transformers.SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SentenceTransformer.__init__() got an unexpected keyword argument 'trust_remote_code'
```

**Comment by GlitChed2k2** [comment]
> The above solution doesn't work for `HuggingFaceEmbeddings`:
> 
> ```python
> from langchain.embeddings import HuggingFaceEmbeddings
> 
> model_name = "jinaai/jina-embeddings-v2-small-en"
> model_kwargs = {"device": "cpu", "trust_remote_code": True}
> encode_kwargs = {
>     "normalize_embeddings": False,
> }
> hf = HuggingFaceEmbeddings(
>     model_name=model_name,
>     model_kwargs=model_kwargs,
>     encode_kwargs=encode_kwargs,
> )
> text = "This is a test document."
> 
> res = hf.embed_query(text)
> 
> print(len(res))
> ```
> 
> Results in the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/nbbaier/grubby-galaxy/main.py", line 9, in <module>
>     hf = HuggingFaceEmbeddings(
>          ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/nbbaier/.pyenv/versions/3.11.0/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 66, in __init__
>     self.client = sentence_transformers.SentenceTransformer(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: SentenceTransformer.__init__() got an unexpected keyword argument 'trust_remote_code'
> ```

Facing the same issue! Any solution for this?

**Comment by gururise** [comment]
Has anyone found a solution to this? Seems like we should be able to pass 'trust_remote_code' into kwargs of the HugginfFaceEmbeddings.

**Comment by Nafay-0** [comment]
`from langchain.embeddings import HuggingFaceEmbeddings
from transformers import AutoModel
model = AutoModel.from_pretrained('jinaai/jina-embeddings-v2-base-en', trust_remote_code=True) 

model_name = "jinaai/jina-embeddings-v2-base-en"
model_kwargs = {'device': 'cpu'}
embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
)`

Found the following work around the problem by loading the embedding model via Transformers class.

**Comment by Nafay-0** [comment]
```
from transformers import AutoModel
model = AutoModel.from_pretrained('jinaai/jina-embeddings-v2-base-en', trust_remote_code=True) 

model_name = "jinaai/jina-embeddings-v2-base-en"
model_kwargs = {'device': 'cpu'}
embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
)
```
Found the following work around for the problem by loading the embedding model via Transformers class.

**Comment by christophfroeschl** [comment]
workaround is good but a fix for the underlying issue pass 

> `trust_remote_code` into kwargs of the HugginfFaceEmbeddings

would be good

**Comment by mallapraveen** [comment]
is this fixed?

**Comment by jcgeo9** [comment]
same isuse here, still waiting for the fix :)

**Comment by manjunathshiva** [comment]
Same issue!  Need fix for the same

**Comment by weissenbacherpwc** [comment]
so there is the same performance when loading the embeddings model with:

from transformers import AutoModel
model = AutoModel.from_pretrained('PATH_TO_LOCAL_EMBEDDING_MODEL_FOLDER', trust_remote_code=True) 

instead of:
from langchain.embeddings import HuggingFaceEmbeddings

model_name = "PATH_TO_LOCAL_EMBEDDING_MODEL_FOLDER"
model_kwargs = {'device': 'cpu'}
embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
)

**Comment by hidacow** [comment]
```
pip install -U sentence-transformers
```
Update sentence-transformers to >=2.3.1 is working for me.
Seems trust_remote_code is not introduced into the constructor of SentenceTransformer before 2.3

**Comment by weissenbacherpwc** [comment]
> This worked for me...
> 
> ```
> model_kwargs = {'trust_remote_code': True}
> embeddings = HuggingFaceEmbeddings(model_name="jinaai/jina-embeddings-v2-base-en",
>                                        model_kwargs=model_kwargs)
> ```

are you using Langchain Huggingface Embeddings here?

**Comment by shimonl20** [comment]
> > This worked for me...
> > ```
> > model_kwargs = {'trust_remote_code': True}
> > embeddings = HuggingFaceEmbeddings(model_name="jinaai/jina-embeddings-v2-base-en",
> >                                        model_kwargs=model_kwargs)
> > ```
> 
> are you using Langchain Huggingface Embeddings here?

Yes

**Comment by KasemOmary** [comment]
`embedding_model = HuggingFaceEmbeddings(model_name="whatever-model-you-are-using", model_kwargs={"trust_remote_code":True}) 
` 

Worked fine for me. As mentioned earlier, be sure to update the versions being used. I used transformer 2.4 model with no issues.

**Comment by ps360pa** [comment]
> ```
> pip install -U sentence-transformers
> ```
> 
> Update sentence-transformers to >=2.3.1 is working for me. Seems trust_remote_code is not introduced into the constructor of SentenceTransformer before 2.3

`pip install -U sentence-transformers==2.4.0 `
it works for 2.4.0 but 2.5.1 the `sentence-transformers` get error

**Comment by ramamimu** [comment]
> `pip install -U sentence-transformers==2.4.0 `

I am still facing another error which seems like similar things
`TypeError: __init__() takes 1 positional argument but 2 were given`

**Comment by risjain** [comment]
@ramamimu As @KasemOmary suggests, try embedding_model = HuggingFaceEmbeddings(model_name="whatever-model-you-are-using", model_kwargs={"trust_remote_code":True})
