### ISSUE TITLE
Langchain classes are not pydantic JSON serializable

### ISSUE THREAD

**Issue by feynmanliang** [hwchase17/langchain#717]
**Context**: I am working on some low-code tooling for langchain and GPT index. As part of this work, I would like to represent langchain classes as JSON, ideally with a JSON Schema to validate it. I know Pydantic's `.json()` and `.schema()` methods aim to fulfill this need.

**Problem**: I expect the following code to produce valid JSON

```py
from langchain import OpenAI
OpenAI().json()
```

Instead, it currently raises the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'type' is not JSON serializable
```

**Comment by feynmanliang** [comment]
Shoulda read the docs... https://langchain.readthedocs.io/en/latest/modules/chains/generic/serialization.html
