### ISSUE TITLE
map_reduce and refine not working with RetrievalQA chain 

### ISSUE THREAD

**Issue by KillerStrike17** [hwchase17/langchain#7347]
### System Info

Langchain Version  - 0.0.201
Platform - Windows 11
Python - 3.10.11

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. load some text documents to a vector store, i used deeplake
2. load the db
3. call the function, summarizer(db,"Summarize the mentions of google according to their AI program")(defined in attached file)
4. run for chain_type as stuff, it will work, for map_reduce it will fail in retrieval QA Bot
[main.zip](https://github.com/hwchase17/langchain/files/11982265/main.zip)

### Expected behavior

it should work for all the chain types and give results

**Comment by KillerStrike17** [comment]
👎, 
Still my query isnt answered..

**Comment by devstein** [comment]
@KillerStrike17 Can you share error logs?

**Comment by KillerStrike17** [comment]
(deeplakelangchain) D:\Github\Video-Summarizer-with-LLMs>python main.py
D:\Anaconda\envs\deeplakelangchain\lib\site-packages\deeplake\util\check_latest_version.py:32: UserWarning: A newer version of deeplake (3.6.8) is available. It's recommended that you update to the latest version using `pip install -U deeplake`.
  warnings.warn(
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/megatron17/video_summarizer_with_llms

hub://megatron17/video_summarizer_with_llms loaded successfully.

Deep Lake Dataset in hub://megatron17/video_summarizer_with_llms already exists, loading from the storage
Dataset(path='hub://megatron17/video_summarizer_with_llms', tensors=['embedding', 'ids', 'metadata', 'text'])

  tensor     htype     shape      dtype  compression
  -------   -------   -------    -------  -------
 embedding  generic  (88, 1536)  float32   None
    ids      text     (88, 1)      str     None
 metadata    json     (88, 1)      str     None
   text      text     (88, 1)      str     None
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\humbug\report.py", line 540, in _hook
    self.error_report(error=exception_instance, tags=tags, publish=publish)
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\humbug\report.py", line 274, in error_report
    traceback.format_exception(
TypeError: format_exception() got an unexpected keyword argument 'etype'

Original exception was:
Traceback (most recent call last):
  File "D:\Github\Video-Summarizer-with-LLMs\main.py", line 27, in <module>
    print(summarizer(db,"Summarize the mentions of google according to their AI program"))
  File "D:\Github\Video-Summarizer-with-LLMs\video_summarizer.py", line 19, in summarizer
    qa = RetrievalQA.from_chain_type(llm=llm,
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 91, in from_chain_type
    combine_documents_chain = load_qa_chain(
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\langchain\chains\question_answering\__init__.py", line 238, in load_qa_chain
    return loader_mapping[chain_type](
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\langchain\chains\question_answering\__init__.py", line 151, in _load_map_reduce_chain
    return MapReduceDocumentsChain(
  File "D:\Anaconda\envs\deeplakelangchain\lib\site-packages\langchain\load\serializable.py", line 61, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MapReduceDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)

**Comment by braun-demv** [comment]
I was able to fix this. 
you need to look, for each chain type (stuff, refine, map_reduce & map_rerank) for the correct input vars for each prompt.

Check the attached file, there I described the issue in detail. And how figured out the issue looking at the Langchain source code for the original/default prompt templates for each Chain type.

[bing_chain_types.md](https://github.com/langchain-ai/langchain/files/12259656/bing_chain_types.md)

**Comment by adityarawat11** [comment]
Hi Braun-demv, 
I tried following your approach for refine. But I still get the following error.
```
ValidationError: 1 validation error for RefineDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)

```
Any clue?
