### ISSUE TITLE
Executor calling CustomTool with no parameter needed insists to call the tool with a parameter coming from nowhere

### ISSUE THREAD

**Issue by jeromemassot** [hwchase17/langchain#7685]
### System Info

langchain==0.0.232
Google Colab

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
def get_current_oil_price():
    ticker_data = yf.Ticker("CL=F")
    recent = ticker_data.history(period='1d')
    return {"price": recent.iloc[0]["Close"], "currency": ticker_data.info["currency"]}
```
```
def get_oil_price_performance(days):
    past_date = datetime.today() - timedelta(days=int(days))
    ticker_data = yf.Ticker("CL=F")
    history = ticker_data.history(start=past_date)
    old_price = history.iloc[0]["Close"]
    current_price = history.iloc[-1]["Close"]
    return {"percent_change": ((current_price - old_price) / old_price) * 100}
```
```
class CurrentOilPriceTool(BaseTool):
    name = "get_oil_price"
    description = "Get the current oil price. No parameter needed from input"


    def _run(self):
        price_response = get_current_oil_price()
        return price_response


    def _arun(self):
        raise NotImplementedError("get_oil_price does not support async")
```

```
class CurrentOilPerformanceTool(BaseTool):
    name = "get_oil_performance"
    description = "Get the current oil price evolution over a given number of days. Enter the number of days."


    def _run(self, days):
        performance_response = get_oil_price_performance(days)
        return performance_response


    def _arun(self):
        raise NotImplementedError("get_oil_performance does not support async") 
```

```
llm = ChatOpenAI(model="gpt-3.5-turbo-0613", temperature=0)

tools = [CurrentOilPriceTool(), CurrentOilPerformanceTool()]

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.OPENAI_FUNCTIONS,
    verbose=True
)
```

`agent.run("What is the oil price?")`

### Expected behavior

```
> Entering new AgentExecutor chain...

Invoking: `get_oil_price`
```

But instead, the executor insists on adding a parameter to the tool function !!!

```
> Entering new AgentExecutor chain...

Invoking: `get_oil_price` with `USD`
```

provoking an obvious error:

`TypeError: CurrentOilPriceTool._run() takes 1 positional argument but 2 were given`

**Comment by jeromemassot** [comment]
Superb and helpful. Good bot, good bot :)

**Comment by lmaddox** [comment]
I'm still having issue with the input args. It seems to happen where there are more than one no-argument functions. In this case, I have two.

"""
Question: What is the purpose of the `my_name_tool`?                                                                                                                                                
                                                                                                                                                                                                    
Thought: The `my_name_tool` is a tool that allows me to learn more about myself. It can provide information about my name, the name of the currently running program, and other details about how I operate.                                                                                                                                                                                            
                                                                                                                                                                                                    
Action:                                                                                                                                                                                             
```                                                                                                                                                                                                 
{                                                                                                                                                                                                   
  "action": "introspect",                                                                                                                                                                           
  "action_input": ""                                                                                                                                                                                
}                                                                                                                                                                                                   
```
"""

```
Traceback (most recent call last):                                                                                                                                                                  
  File "/home/lmaddox/.local/lib/python3.10/site-packages/langchain/agents/agent.py", line 1224, in _iter_next_step
    yield self._perform_agent_action(
  File "/home/lmaddox/.local/lib/python3.10/site-packages/langchain/agents/agent.py", line 1246, in _perform_agent_action
    observation = tool.run(
  File "/home/lmaddox/.local/lib/python3.10/site-packages/langchain_core/tools.py", line 452, in run
    raise e
  File "/home/lmaddox/.local/lib/python3.10/site-packages/langchain_core/tools.py", line 406, in run
    parsed_input = self._parse_input(tool_input)
  File "/home/lmaddox/.local/lib/python3.10/site-packages/langchain_core/tools.py", line 299, in _parse_input
    key_ = next(iter(input_args.__fields__.keys()))
StopIteration
```
