### ISSUE TITLE
    raise AttributeError(name) from None AttributeError: OPENAI_FUNCTIONS

### ISSUE THREAD

**Issue by iamsmthing** [hwchase17/langchain#7833]
### System Info

![Screenshot 2023-07-17 184319](https://github.com/hwchase17/langchain/assets/90586668/e454e70a-66da-40bd-b3c7-92d26caeccea)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The above code snippet  is not working when i'm trying to give LLM an input via streamlit or flask. Error occurs when we are trying to use:``` agent_type=AgentType.OPENAI_FUNCTIONS,```. It's Raising the error like as Below:
```
    raise AttributeError(name) from None
AttributeError: OPENAI_FUNCTIONS
```

### Expected behavior

I expect that when we give input from either post request via FLASK or via streamlit input box, it should accept the input and should pass on this input to agent to run it and give the result accordingly,.

**Comment by thedamnedrhino** [comment]
Please include the full stack trace.

**Comment by iamsmthing** [comment]
> 
Here you can find the whole stack trace.
(.venv) D:\df_agent_openAI>flask run
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 1050, in main
    cli.main()
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 911, in run_command
    raise e from None
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "D:\df_agent_openAI\app.py", line 52, in <module>
    agent_type=AgentType.OPENAI_FUNCTIONS,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.rai\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 786, in __getattr__
    raise AttributeError(name) from None
AttributeError: OPENAI_FUNCTIONS

**Comment by xones267** [comment]
I am facing the same issue

**Comment by thedamnedrhino** [comment]
Check `langchain.agents.agent_types.AgentType` on your local langchain installation and see whether the `OPENAI_FUNCTIONS` attribute is there. You can see that it's [there in the latest version](https://github.com/langchain-ai/langchain/blob/76102971c056bb277bf394068c98fb05ee2fb07d/libs/langchain/langchain/agents/agent_types.py#L16C5-L16C42).
